### PR TITLE
Added other useful functions:

### PR DESCRIPTION
**Pull request by minhnc**
- logEventWithNameAndData // logEventWithNameAndData('event_name', { msg: 'hi' });
- updateUserWithAttributes     // updateUserWithAttributes({ fname: 'John', lname: 'Doe' });
- setDeviceToken                     // setDeviceToken('token', Ti.App.Android.R.drawable.appicon);

### CODE REVIEW

**Comment by jerodfritz** [comment]
Hey - Thanks for the PR.  Would you mind updating the Readme, bumping the version number and providing a new dist with these changes.

**Comment by minhnc** [comment]
Hey - I think there's something wrong with my env - the module works well on android 5, but got this error on android 6: 

`lib/arm/libti.intercom.android.so: has text relocations`

I also tried to create a module, then package and run with a sample project.. still got _.so has text relocations_

This is my env: 
- android-ndk-r9d
- Android SDK 5.0.x (API 21), 6.0.x (API 23)
- Android SDK Tools Rev 23
- Android SDK Platform-tools/Build-tools Rev 21
- Appcelerator Studio, build: 4.5.0.201602170821
- Titanium CLI: 5.0.6
- Java Development Kit: 1.7.0_80
- Mac OS X 10.11.2

Your build 1.0.1 works well on android 6. Could you please share your env settings?

**Comment by jerodfritz** [comment]
I won't know my exact environment until I get back to that machine later this week.  I'll let you know then - Jerod

**Comment by jerodfritz** [comment]
**ndk**
android-ndk-r8d

**build.proprties**
titanium.platform=/Users/jerodfritz/Library/Application Support/Titanium/mobilesdk/osx/5.1.1.GA/android
android.platform=/Applications/Android/platforms/android-23
google.apis=/Applications/Android/add-ons/addon-google_apis-google-23

**ti**
Appcelerator Studio, build: 4.5.0.201602170831
Titanium Command-Line Interface, CLI version 5.0.6, Titanium SDK version 5.2.2.GA

**os**
OSX El Capitan 10.11.4

**Comment by minhnc** [comment]
Thank you for your information. I tried to install android-ndk-r8d, also setup the same build.proprties, but still got `.so: has text relocations` error. I'll report this issue to APPC soon. In the meantime, it'd be great if you could help to make a build on your env.

**Comment by minhnc** [comment]
Finally it works after I downgraded the build tools from 21.1.0 to 21.0.0 :)

**Comment by jerodfritz** [comment]
Excellent.  Will you replace the ti.intercom.android-android-1.0.1.zip with your ti.intercom.android-android-1.0.2.zip and update the Readme to include the new functions

**Comment by minhnc** [comment]
done!

**Comment by jerodfritz** [comment]
Looks good.  I'll merge.  Thank you.

There has got to be a way to retrieve the appicon from within the module rather than having to pass it along as a parameter with setDeviceToken

**Comment by minhnc** [comment]
Yes that's possible to retrieve the appicon from within the module. But I think user might want to make this configurable.

**Pull request merged**
